Revert "NXP-19899: avoid static dependency to runtime to prevent error 'java.lang.NoClassDefFoundError: Could not initialize class org.nuxeo.ecm.core.storage.dbs.DBSSession' in tests"
This reverts commit c1782ae9e2d46adff55489959fc02c3aa0d7a407.